# Generated by Django 2.2.5 on 2019-09-26 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the type of animal (e.g. cat', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Breeder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.TextField(default='', help_text='A few things the pet likes', max_length=1000)),
                ('status', models.CharField(blank=True, choices=[('s', 'Sold'), ('u', 'Unavailable'), ('a', 'Available'), ('r', 'Reserved')], default='a', help_text='status of the pet', max_length=1)),
                ('animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Animal')),
            ],
        ),
    ]
