# Generated by Django 2.2.5 on 2019-09-26 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190926_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animals'},
        ),
        migrations.RemoveField(
            model_name='pet',
            name='breed',
        ),
        migrations.AddField(
            model_name='animal',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.Animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Animal'),
        ),
        migrations.AlterUniqueTogether(
            name='animal',
            unique_together={('parent',)},
        ),
        migrations.DeleteModel(
            name='Breed',
        ),
    ]
